# Docker file
# Suggest bot for telegram
# Author fet1sov <prodaugust21@gmail.com>

FROM node:18-alpine as builder
RUN npm cache clean –force

WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install

# Building the frontend part
CMD ["npm", "run", "start"]